Name:           cbflib 
Version:        0.9.6
Release:        1%{?dist}
Summary:        C libraries for handling crystallographic binary format files

License:        LGPL
URL:            www.bernstein-plus-sons.com/software/CBF
Source0:        https://github.com/yayahjb/cbflib

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  gcc-gfortran
BuildRequires:  pcre-devel
BuildRequires:  python2-devel
BuildRequires:  zlib-devel
Requires:       libaec
Requires:       libaec-devel
Requires:	hdf5-devel

%description
CBFLib is a library of C functions for reading and writing 2D area detector\
images in crystallographic binary format (CBF). These shared libaries are\
required for fast decompression of hdf5 images from Dectris Eiger detectors\
for MX processing applications. The software is actively maintained by\
Herbert J. Bernstein (yayahjb@gmail.com). Package generated by Dale Kreitler\
(dkreitler@bnl.gov) for deployment on NSLS-II MX beamline workstations and\
compute nodes running RHEL8. Initial source git cloned from Herbert's\
repository (https://github.com/yayahjb/cbflib).


%prep
##%setup -q -n %{name}
cd %{_topdir}/BUILD
rm -rf %{name}
cp -rf %{_topdir}/SOURCES/%{name} .
cd %{name}
sed -i 's/^CIFLIB_DONT_USE_PYCIFRW*no*/CIFLIB_DONT_USE_PYCIFRW ?= yes/' Makefile

%build
rm -rf %{buildroot}
cd %{_topdir}/BUILD/%{name}
make all
make shared

%install
export QA_SKIP_RPATHS=1
mkdir -p %{buildroot}%{_libdir}
cp -rfa %{_topdir}/BUILD/%{name}/solib/libcbf.so %{buildroot}%{_libdir}
mkdir -p %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/cbf*h %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/global.h %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/md5.h %{buildroot}%{_includedir}

%files
%{_libdir}/libcbf.so
%{_includedir}/*

%clean
rm -rf %{_topdir}/BUILD/%{name}

#%license add-license-file-here
#%doc add-docs-here

%changelog
* Fri Aug  6 2021 dkreitler
initial commit- 
