Name:           cbflib 
Version:        0.9.6
Release:        1%{?dist}
Summary:        C libraries for handling crystallographic binary format files

License:        LGPL
URL:            www.bernstein-plus-sons.com/software/CBF

# use git clone https://github.com/yayahjb/cbflib to generate SOURCE dir
# prepare Makefile in source with following:
# sed -i 's/^CBFLIB_DONT_USE_PYCIFRW*no*/CBFLIB_DONT_USE_PYCIFRW ?= yes/' Makefile
# sed -i 's/^CBFLIB_DONT_USE_LOCAL_HDF5*no*/CBFLIB_DONT_USE_LOCAL_HDF5 ?= yes/' Makefile

# Herbert configured CBFlib Makefile to download external packages required
# to build with wget, which caused autobuild pipeline in mock environment
# to fail. Therefore these packages are predownloaded as tar.gz and extracted
# as multiple sources with the setup macro.

# These variables now commented out in Makefile:
# DOWNLOAD
# PLYURL
# REGEX_URL
# TIFF_URL
# LZ4_URL
# BSHUFURL
#
# And in Makefile macros that handle these variables, flanking rm commands such
# as, rm -rf $(LZ4), are now commented out. Source extraction handled by rpm
# builder now so they are unnecessary.

Source:        cbflib.tar.gz
Source1:        ply-3.2.tar.gz
Source2:        pcre-8.38.tar.gz
Source3:        HDF5Plugin_14Aug20.tar.gz
Source4:        bitshuffle-0.2.2.1_15Jun16.tar.gz
Source5:        tiff-4.0.6_rev_3Nov16.tar.gz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  gcc-gfortran
BuildRequires:  pcre-devel
BuildRequires:  zlib-devel
BuildRequires:  m4
BuildRequires:  hdf5-devel
Requires:       libaec
Requires:       libaec-devel
Requires:	hdf5-devel

%description
CBFLib is a library of C functions for reading and writing 2D area detector\
images in crystallographic binary format (CBF). These shared libaries are\
required for fast decompression of hdf5 images from Dectris Eiger detectors\
for MX processing applications. The software is actively maintained by\
Herbert J. Bernstein (yayahjb@gmail.com). Package generated by Dale Kreitler\
(dkreitler@bnl.gov) for deployment on NSLS-II MX beamline workstations and\
compute nodes running RHEL8. Initial source git cloned from Herbert's\
repository (https://github.com/yayahjb/cbflib).

%prep
%setup -q -n %{name}
%setup -D -a 1 -n %{name}
%setup -D -a 2 -n %{name}
%setup -D -a 3 -n %{name}
%setup -D -a 4 -n %{name}
%setup -D -a 5 -n %{name}
#cp %{_topdir}/SOURCES/ply-3.2.tar.gz .
#cp %{_topdir}/SOURCES/pcre-8.38.tar.gz .
#cp %{_topdir}/SOURCES/HDF5Plugin_14Aug20.tar.gz .
#cp %{_topdir}/SOURCES/bitshuffle-0.2.2.1_15Jun16.tar.gz .
#cp %{_topdir}/SOURCES/tiff-4.0.6_rev_3Nov16.tar.gz .

%build
cd %{_topdir}/BUILD/%{name}
make all
make shared

%install
export QA_SKIP_RPATHS=1
mkdir -p %{buildroot}%{_libdir}
cp -rfa %{_topdir}/BUILD/%{name}/solib/libcbf.so %{buildroot}%{_libdir}
mkdir -p %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/cbf*h %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/global.h %{buildroot}%{_includedir}
cp %{_topdir}/BUILD/%{name}/include/md5.h %{buildroot}%{_includedir}

%files
%{_libdir}/libcbf.so
%{_includedir}/*

%clean
rm -rf %{_topdir}/BUILD/%{name}

#%license add-license-file-here
#%doc add-docs-here

%changelog
* Fri Aug  6 2021 dkreitler
initial commit- 
